apiVersion: apps/v1
kind: Deployment
metadata:
  name: tazz-demo-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 784638312003.dkr.ecr.us-east-2.amazonaws.com/my-eks-container-tazz
          ports:
            - containerPort: 3000