apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: web # selector will match the selector in the deployment
  ports:
    - nodePort: 31479
      port: 8080  # service port
      targetPort: 3000 # Container deployment exposed port